### PR TITLE
all: use quicktest

### PR DESCRIPTION
**Pull request by mhilton**
Also add module support.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/candidclient/4/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/candidclient/5/

**Review by rogpeppe — APPROVED** [review]
LGTM, thanks!

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.theblues.io:8080/job/candidclient-merge

**Pull request merged**
